http:
  routers:
    unstract-frontend:
      rule: Host(`{{ env "UNSTRACT_HOST" }}`) && !PathPrefix(`/api/v1`) && !PathPrefix(`/deployment`) && !PathPrefix(`/public`)
      service: unstract-frontend
      entryPoints:
        - http
    unstract-backend:
      rule: Host(`{{ env "UNSTRACT_HOST" }}`) && (PathPrefix(`/api/v1`) || PathPrefix(`/deployment`) || PathPrefix(`/public`))
      service: unstract-backend
      entryPoints:
        - http
  services:
    unstract-frontend:
      loadBalancer:
        servers:
          - url: http://unstract-frontend:80
    unstract-backend:
      loadBalancer:
        servers:
          - url: http://unstract-backend:8000
